### PR TITLE
chore: Added spellcheck action and dev instructions

### PR DESCRIPTION
**Pull request by daviroo**
As per suggestion here https://github.com/Extheoisah/hxckr-core/pull/15#discussion_r1745925505

### CODE REVIEW

**Comment by Extheoisah** [comment]
Thanks for picking this up @daviroo 
In the initialization step, one has to install npm the dep globally. Could we use something more native to rust and that wouldn't require global installation? Something we could add to the rust project and call it in ci e.g. https://github.com/crate-ci/typos
what do you think?

**Comment by daviroo** [comment]
Yeah that's probably better.  I'm not very familiar with the workflows in Rust though.  Do you know how to build that into the github actions easily? (it probably is easy I just haven't looked into it)

**Comment by Extheoisah** [comment]
@daviroo I have switched it to the typos crate https://github.com/Extheoisah/hxckr-core/pull/16/commits/a4aeeb5e6691c1d9192aa0d9c3d7de5f789349a5

**Review by nully0x — APPROVED** [review]
LGTM

**Pull request merged**
